version: "3.9"

services:
  backend:
    network_mode: "host"

    build:
      context: ./Back-End
      dockerfile: Dockerfile
    image: app-back:latest
    container_name: app-back
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb+srv://nicolombe:admin@cluster.btoi0.mongodb.net/ressource_relationnelle

    restart: unless-stopped

  frontend:
    network_mode: "host"

    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: app-front:latest
    container_name: app-front
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
