version: "3.9"

services:
  # --------- FRONT (React, servi en HTTPS par Nginx) ----------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: app-front:latest
    container_name: app-front
    ports:
      - "443:443"   # Front dispo en HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped

  # --------- CERTBOT ----------
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: "no"

  # --------- BACK (HTTPS direct sur 5001) ----------
  backend:
    build:
      context: ./Back-End
      dockerfile: Dockerfile
    image: app-back:latest
    container_name: app-back
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb+srv://nicolombe:admin@cluster.btoi0.mongodb.net/ressource_relationnelle
    volumes:
    - ./certbot/conf:/etc/letsencrypt:ro   # on monte l’arborescence LE en RO
    restart: unless-stopped


networks:
  default:
    name: webnet
    driver: bridge

