name: 🐛 Rapport de Bug
description: Signaler un bug ou un problème dans RE-Source-Relationnelle
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de remplir ce rapport de bug pour RE-Source-Relationnelle !
  - type: dropdown
    id: component
    attributes:
      label: Composant concerné
      description: Quelle partie de l'application est affectée par ce bug ?
      options:
        - Frontend - Authentification
        - Frontend - Feed des ressources
        - Frontend - Création/édition de ressources
        - Frontend - Commentaires
        - Frontend - Catégories
        - Frontend - Recherche
        - Frontend - Backoffice admin
        - Backend - API Ressources
        - Backend - API Authentification
        - Backend - API Catégories
        - Backend - API Utilisateurs
        - Backend - API Commentaires
        - Autre
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environnement
      description: Dans quel environnement avez-vous rencontré ce problème ?
      options:
        - Développement
        - Test
        - Production
    validations:
      required: true
  - type: dropdown
    id: role
    attributes:
      label: Rôle utilisateur
      description: Avec quel type de compte avez-vous rencontré ce problème ?
      options:
        - Utilisateur non connecté
        - Utilisateur standard (Citoyen)
        - Administrateur
        - Super-administrateur
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Que s'est-il passé ?
      description: Décrivez le bug de manière claire et concise.
      placeholder: Décrivez le comportement observé et le comportement attendu.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Étapes pour reproduire
      description: Comment pouvons-nous reproduire ce bug ?
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '....'
        3. Faire défiler jusqu'à '....'
        4. Observer l'erreur
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs pertinents
      description: Copiez et collez les logs pertinents si disponibles (console navigateur, logs backend, etc.)
      render: shell
  - type: textarea
    id: additional
    attributes:
      label: Informations supplémentaires
      description: Tout contexte supplémentaire sur le problème (navigateur utilisé, appareil, etc.)
